version: "3.3"

services:
  # see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  elasticsearch:
    image: elasticsearch
    build:
      dockerfile: es6.Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    environment:
     "cluster.name": "localdev"
     "discovery.type": "single-node"
     ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - es
    depends_on:
      - elasticsearch
    environment:
      LOGGING_QUIET: "true"

volumes:
  esdata:

networks:
  es:
