version: "3.3"

services:
  # see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  elasticsearch:
    # use elasticsearch/elasticsearch:7.10.0-arm64 for ARM architecture
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    environment:
      - cluster.name=localdev
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9200
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.0
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - es
    depends_on:
      - elasticsearch
    environment:
      LOGGING_QUIET: "true"
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200
      network.host: 0.0.0.0

volumes:
  esdata:

networks:
  es:
